In [14]:
import numpy as np
import pandas as pd

def dcg_at_k(r, k, method=1):
    r = np.asfarray(r)[:k]
    return np.sum(r / np.log2(np.arange(2, len(r) + 2)))


def ndcg_at_k(r, k=5, method=1):
    dcg_max = dcg_at_k(sorted(r, reverse=True), k, method)
    return dcg_at_k(r, k, method) / dcg_max


def score_predictions(preds, truth):
    """
    preds: pd.DataFrame
      one row for each observation, one column for each prediction.
      Columns are sorted from left to right descending in order of likelihood.
    truth: pd.Series
      one row for each obeservation.
    """
    r = pd.DataFrame(0, index=preds.index, columns=preds.columns, dtype=np.float64)
    for col in preds.columns:
        r[col] = (preds[col] == truth)

    score = pd.Series(r.apply(ndcg_at_k, axis=1, reduce=True), name='score')
    return score

In [15]:
preds = pd.DataFrame([['af','asf','US','NDF'],['FR','GR','asf','NDF'],['FR','FR','asfa','NDF'],['GR','NDF','FR','NDF']])
truth = pd.Series(['US','GR','FR','NDF'])
scores=pd.concat([truth,preds,score_predictions(preds, truth)],axis=1)
scores.columns=['truth','pred1','pred2','pred3','pred4','score']
scores

C:\Users\Asyariati\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: FutureWarning: The reduce argument is deprecated and will be removed in a future version. You can specify result_type='reduce' to try to reduce the result to the original dimensions


truth pred1 pred2 pred3 pred4     score
0    US    af   asf    US   NDF  0.500000
1    GR    FR    GR   asf   NDF  0.630930
2    FR    FR    FR  asfa   NDF  1.000000
3   NDF    GR   NDF    FR   NDF  0.650921

In [16]:
score_predictions(preds, truth)

C:\Users\Asyariati\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: FutureWarning: The reduce argument is deprecated and will be removed in a future version. You can specify result_type='reduce' to try to reduce the result to the original dimensions


0    0.500000
1    0.630930
2    1.000000
3    0.650921
Name: score, dtype: float64

In [36]:
a=pd.DataFrame(0, index=preds.index, columns=preds.columns, dtype=np.float64)

In [37]:
for col in preds.columns:
        a[col] = (preds[col] == truth)

In [41]:
a

0      1      2      3
0  False  False   True  False
1  False   True  False  False
2   True   True  False  False
3  False   True  False   True

In [61]:
np.asfarray(sorted(a,reverse=True))

array([3., 2., 1., 0.])

In [60]:
np.log2(np.arange(2, len(a) + 2))

array([1.        , 1.5849625 , 2.        , 2.32192809])

In [62]:
np.asfarray(sorted(a,reverse=True))/np.log2(np.arange(2, len(a) + 2))

array([3.        , 1.26185951, 0.5       , 0.        ])

In [63]:
np.asfarray(a)

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 1.]])

In [64]:
np.log2(np.arange(2, len(a) + 2))

array([1.        , 1.5849625 , 2.        , 2.32192809])

In [65]:
np.asfarray(a)/np.log2(np.arange(2, len(a) + 2))

array([[0.        , 0.        , 0.5       , 0.        ],
       [0.        , 0.63092975, 0.        , 0.        ],
       [1.        , 0.63092975, 0.        , 0.        ],
       [0.        , 0.63092975, 0.        , 0.43067656]])